import { AIHelperComponentArray } from "./AIHelperComponent";
import { TribeComponentArray, InventoryComponentArray, HealthComponentArray, ItemComponentArray, TotemBannerComponentArray, TreeComponentArray, BerryBushComponentArray, InventoryUseComponentArray, BoulderComponentArray, IceShardComponentArray, CowComponentArray, WanderAIComponentArray, EscapeAIComponentArray, FollowAIComponentArray, CactusComponentArray, TribeMemberComponentArray, PlayerComponentArray, TribesmanComponentArray, TombstoneComponentArray, ZombieComponentArray, SlimewispComponentArray, SlimeComponentArray, ArrowComponentArray, YetiComponentArray, SnowballComponentArray, FishComponentArray, FrozenYetiComponentArray, RockSpikeProjectileComponentArray, CookingComponentArray, ThrowingProjectileComponentArray, HutComponentArray, SlimeSpitComponentArray, DoorComponentArray, GolemComponentArray, IceSpikesComponentArray, PebblumComponentArray, BlueprintComponentArray, TurretComponentArray, AmmoBoxComponentArray, ResearchBenchComponentArray } from "./ComponentArray";
import { PhysicsComponentArray } from "./PhysicsComponent";
import { StatusEffectComponentArray } from "./StatusEffectComponent";

export function resetComponents(): void {
   TribeComponentArray.reset();
   InventoryComponentArray.reset();
   HealthComponentArray.reset();
   ItemComponentArray.reset();
   TotemBannerComponentArray.reset();
   TreeComponentArray.reset();
   BerryBushComponentArray.reset();
   InventoryUseComponentArray.reset();
   BoulderComponentArray.reset();
   IceShardComponentArray.reset();
   CowComponentArray.reset();
   WanderAIComponentArray.reset();
   EscapeAIComponentArray.reset();
   FollowAIComponentArray.reset();
   CactusComponentArray.reset();
   TribeMemberComponentArray.reset();
   PlayerComponentArray.reset();
   TribesmanComponentArray.reset();
   TombstoneComponentArray.reset();
   ZombieComponentArray.reset();
   SlimewispComponentArray.reset();
   SlimeComponentArray.reset();
   ArrowComponentArray.reset();
   YetiComponentArray.reset();
   SnowballComponentArray.reset();
   FishComponentArray.reset();
   FrozenYetiComponentArray.reset();
   RockSpikeProjectileComponentArray.reset();
   CookingComponentArray.reset();
   ThrowingProjectileComponentArray.reset();
   HutComponentArray.reset();
   SlimeSpitComponentArray.reset();
   DoorComponentArray.reset();
   GolemComponentArray.reset();
   IceSpikesComponentArray.reset();
   PebblumComponentArray.reset();
   BlueprintComponentArray.reset();
   TurretComponentArray.reset();
   AmmoBoxComponentArray.reset();
   ResearchBenchComponentArray.reset();
   PhysicsComponentArray.reset();
   StatusEffectComponentArray.reset();
   AIHelperComponentArray.reset();
}